### ISSUE TITLE
Error mapping cities

### ISSUE THREAD

**Issue by MrChristopherWilliams** [lewagon/redux-cities#1]
I've downloaded this and tried to run but I get an error when mapping the cities. Specifically, the following function in containers/city_list.jsx fails because cities is undefined. Unfortunately I can't work out why.

`renderList() {
    return this.props.cities.map((city) => {
      return (
        <City key={city.name} city={city} />
      );
    });
  }`

**Comment by MrChristopherWilliams** [comment]
OK I think the problem is to do with src/index.jsx. When I remove lines 12-15, import rootReducer from './reducers/index' and change reducers in line 19 to rootReducer it seems to work. 

I guess this is because the combineReducer functions was being performed twice because it's also performed in reducers/index.js. Please feel free to correct me as I'm still completely new to React and Redux

**Comment by santiagosan93** [comment]
Hey @MrChristopherWilliams 
It kinda looks like you are in the wrong folder. If you delete lines 12-15 from the current  src/index.jsx, you'll create a massive syntax error. Are you sure you are speaking about the correct file?  Maybe you can take a look now and let us know if the current version of this code  works for you. Everything seems to be working on my end. 

This is how the current src/index.jsx looks like 

```javascript
// external modules
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducers from './reducers';

// internal modules
import App from './components/app';
import '../assets/stylesheets/application.scss';

// render an instance of the component in the DOM
ReactDOM.render(
  <Provider store={createStore(reducers)}>
    <App />
  </Provider>,
  document.querySelector('.container')
);

```

I'm closing since it looks like an error on your end.  Please let me know if otherwise. Thank you 🙏
